### ISSUE TITLE
Avni Stock Reports

### ISSUE THREAD

**Issue by arjunk** [avniproject/avniStock#3]
Reports to be created in Metabase

Report 1 : Stock Regiser 1
Description : This report is like a stock ledger to be seen for each centre
Columns : Month and year | Location | Drug name | Batch number | Expiry date | Qty Received | Qty Issued | Stock in hand
Filter : Location | Year | Month | Drug name
Logic : Do not show batches closed in previous month

Report 2 : Stock Register 2
Description : This report is to know availability of stock at each centre
Columns : Location | Drug name | Year and month | Opening balance | Earliest Expiry date | Qty received during month | Utilisation during month | Qty Returned | Balance at end of month
Filter : Location | Year | Month | Drug name

- [x] Restock needed - Same as offline report available in mobile app

- [x] Expiry status - Same as offline report available in mobile app

**Comment by nupoorkhandelwal** [comment]
**Notes**: We dont have any feild or parameter to calculate 'Utilisation during month',so adding it as 0 in the report
