### ISSUE TITLE
Create production ready org

### ISSUE THREAD

**Issue by arjunk** [avniproject/avniStock#4]
4 Locations and 4 catchments
1. Bhawanipatna
2. Kaniguma
3. Kerpai
4. Silet

Create drugs as subjects for all the 3 centres
https://docs.google.com/spreadsheets/d/1mfHyzGHdLqiECyeEq6mndnU_5O9okHuk/edit#gid=371111551

Users
Amarsing- Bhawanipatna
Chanchala- Silet
Anup- Kaniguma
Sarojini- Kerpai

For all the users put these details
Vikram Paswan ssvpaswan@gmail.com 6206883324

**Comment by nupoorkhandelwal** [comment]
Remaining tasks -
1. Creating users . reason - insufficient details
2. uploading drugs. reason - restock quantity not yet shared

**Comment by nupoorkhandelwal** [comment]
Drugs uploaded for Bhwanipatna. 
CSV files for drug upload is ready. Waiting for the restock value to confirm for the other three locations.

**Comment by nupoorkhandelwal** [comment]
Uploaded files -- https://drive.google.com/drive/folders/1Y2XizsSY8IABlANXh_BeyxGhM6LMmy7w

**Comment by garimadosar5** [comment]
**QA Notes -** 
- there are total 568 drugs in CSV but 426 are uploaded.
