### ISSUE TITLE
New Drug import

### ISSUE THREAD

**Issue by arjunk** [avniproject/avniStock#6]
[https://app.zenhub.com/files/414947797/f29fdc22-867b-419d-bbfc-4f8fd9138ff3/download](https://app.zenhub.com/files/414947797/f29fdc22-867b-419d-bbfc-4f8fd9138ff3/download)

Tasks
- Upload drugs
- Not all drugs are tablets. That needs to be fixed.

**Comment by garimadosar5** [comment]
Uploaded data - 
https://drive.google.com/drive/folders/1Y2XizsSY8IABlANXh_BeyxGhM6LMmy7w
