### ISSUE TITLE
Performance: Adding and removing products is slow

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avniStock#8]
https://avni.freshdesk.com/a/tickets/2458

https://drive.google.com/file/d/1mzCRce6UHMcPLTSvKc9L6YsN6IgKB5Vu/view

**Comment by 1t5j0y** [comment]
Fix: Used modal display when there are lot of products to be shown

~APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/avni-stock-staging-6f67-2023-03-09-12-26-39.apk~

**Comment by 1t5j0y** [comment]
Will need to target API level 31 for upload on play store. Will do that as well.

**Comment by 1t5j0y** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/avni-stock-staging-e6f8-2023-03-09-13-55-53.apk

**Comment by vinayvenu** [comment]
Testing notes: Test for functionality with staging apk. Performance requires more data, so it is worth testing with prod data instead.

**Comment by 1t5j0y** [comment]
Prod APK:
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/avni-stock-prod-e6f8-2023-03-10-11-32-24.apk

**Comment by AchalaBelokar** [comment]
- [ ] On staging  app is crashing.

- [ ] and also app performce is very slow
